### ISSUE TITLE
Azure VE failing during runtime-init install of packages

### ISSUE THREAD

**Issue by JeffGiroux** [F5Networks/f5-bigip-runtime-init#12]
I'm using runtime init along with CST2 Azure templates. I crafted my own standalone BIG-IP version and am using runtime init examples slightly modified from the CST2 autoscale example to work with a standalone BIG-IP instead. During deployment attempts, I noticed multiple times that the big-ip doesn't finish onboarding in Azure and fails the template ARM job. When I look at /var/log/cloud, I see a consistent pattern where the install stops on the RPM package install.

Where can I look for further troubleshooting?

snippet...
2021-03-27T00:34:23.667Z [25567]: info: Executing install operations.
2021-03-27T00:34:23.680Z [25567]: info: Installing - do 1.16.0
2021-03-27T00:34:26.334Z [25567]: info: Installing - as3 3.23.0

Nothing else exists in /var/log/cloud/startup-script.log past that point.

BIG-IP = 15.1.2.1
Using my standalone example here
https://github.com/JeffGiroux/f5-azure-arm-templates-v2/tree/main/examples/standalone/payg

**Comment by JeffGiroux** [comment]
For ticket purposes, here's the text of the runtime init yaml file

```
---
extension_packages:
  install_operations:
    - extensionHash: 536eccb9dbf40aeabd31e64da8c5354b57d893286ddc6c075ecc9273fcca10a1
      extensionType: do
      extensionVersion: 1.16.0
    - extensionHash: de615341b91beaed59195dceefc122932580d517600afce1ba8d3770dfe42d28
      extensionType: as3
      extensionVersion: 3.23.0
    - extensionHash: 333e11a30ba88699ac14bc1e9546622540a5e889c415d5d53a8aeaf98f6f872e
      extensionType: ts
      extensionVersion: 1.15.0
extension_services:
  service_operations:
    - extensionType: do
      type: url
      value: 'https://raw.githubusercontent.com/JeffGiroux/f5-azure-arm-templates-v2/main/examples/standalone/bigip-configurations/standalone_do_payg.json'
    - extensionType: as3
      type: url
      value: 'https://raw.githubusercontent.com/JeffGiroux/f5-azure-arm-templates-v2/main/examples/standalone/bigip-configurations/standalone_as3.json'
    - extensionType: ts
      type: url
      value: 'https://raw.githubusercontent.com/JeffGiroux/f5-azure-arm-templates-v2/main/examples/standalone/bigip-configurations/standalone_ts.json'
post_onboard_enabled: []
pre_onboard_enabled:
  - name: provision_rest
    type: inline
    commands:
      - /usr/bin/setdb provision.extramb 1000
      - /usr/bin/setdb restjavad.useextramb true
      - '/usr/bin/curl -s -f -u admin: -H "Content-Type: application/json" -d ''{"maxMessageBodySize":134217728}'' -X POST http://localhost:8100/mgmt/shared/server/messaging/settings/8100 | jq .'
  - name: provision_modules
    type: inline
    commands:
      - echo 'sys provision asm { level nominal }' >> bigip_base.conf
runtime_parameters:
  - name: HOST_NAME
    type: metadata
    metadataProvider:
      environment: azure
      type: compute
      field: name
```

**Comment by JeffGiroux** [comment]
restnoded logs at same time marker...notice nothing after DO logs

```
Sat, 27 Mar 2021 00:34:24 GMT - finest: socket 13 closed
Sat, 27 Mar 2021 00:34:24 GMT - finest: [LoaderWorker] triggered at path:  /var/config/rest/iapps/f5-declarative-onboarding/nodejs/restWorker.js
Sat, 27 Mar 2021 00:34:24 GMT - severe: [LoaderWorker] JSHINT issues encountered in file /var/config/rest/iapps/f5-declarative-onboarding/nodejs/restWorker.js, 12 errors
Sat, 27 Mar 2021 00:34:24 GMT - severe: [LoaderWorker] /var/config/rest/iapps/f5-declarative-onboarding/nodejs/restWorker.js: line 521, col 5, Option 'validthis' can't be used in a global scope.
Sat, 27 Mar 2021 00:34:24 GMT - severe: [LoaderWorker] /var/config/rest/iapps/f5-declarative-onboarding/nodejs/restWorker.js: line 601, col 5, Option 'validthis' can't be used in a global scope.
Sat, 27 Mar 2021 00:34:24 GMT - severe: [LoaderWorker] /var/config/rest/iapps/f5-declarative-onboarding/nodejs/restWorker.js: line 628, col 5, Option 'validthis' can't be used in a global scope.
Sat, 27 Mar 2021 00:34:24 GMT - severe: [LoaderWorker] /var/config/rest/iapps/f5-declarative-onboarding/nodejs/restWorker.js: line 686, col 5, Option 'validthis' can't be used in a global scope.
Sat, 27 Mar 2021 00:34:24 GMT - severe: [LoaderWorker] /var/config/rest/iapps/f5-declarative-onboarding/nodejs/restWorker.js: line 743, col 5, Option 'validthis' can't be used in a global scope.
Sat, 27 Mar 2021 00:34:24 GMT - severe: [LoaderWorker] /var/config/rest/iapps/f5-declarative-onboarding/nodejs/restWorker.js: line 876, col 5, Option 'validthis' can't be used in a global scope.
Sat, 27 Mar 2021 00:34:24 GMT - severe: [LoaderWorker] /var/config/rest/iapps/f5-declarative-onboarding/nodejs/restWorker.js: line 915, col 5, Option 'validthis' can't be used in a global scope.
Sat, 27 Mar 2021 00:34:24 GMT - severe: [LoaderWorker] /var/config/rest/iapps/f5-declarative-onboarding/nodejs/restWorker.js: line 1005, col 5, Option 'validthis' can't be used in a global scope.
Sat, 27 Mar 2021 00:34:24 GMT - severe: [LoaderWorker] /var/config/rest/iapps/f5-declarative-onboarding/nodejs/restWorker.js: line 1117, col 5, Option 'validthis' can't be used in a global scope.
Sat, 27 Mar 2021 00:34:24 GMT - severe: [LoaderWorker] /var/config/rest/iapps/f5-declarative-onboarding/nodejs/restWorker.js: line 1175, col 5, Option 'validthis' can't be used in a global scope.
Sat, 27 Mar 2021 00:34:24 GMT - severe: [LoaderWorker] /var/config/rest/iapps/f5-declarative-onboarding/nodejs/restWorker.js: line 1216, col 5, Option 'validthis' can't be used in a global scope.
Sat, 27 Mar 2021 00:34:24 GMT - severe: [LoaderWorker] /var/config/rest/iapps/f5-declarative-onboarding/nodejs/restWorker.js: line 1317, col 5, Option 'validthis' can't be used in a global scope.
Sat, 27 Mar 2021 00:34:25 GMT - info: [f5-declarative-onboarding: restWorker.js] Created Declarative onboarding worker
Sat, 27 Mar 2021 00:34:25 GMT - info: starting /shared/declarative-onboarding
Sat, 27 Mar 2021 00:34:25 GMT - finest: socket 184 closed
Sat, 27 Mar 2021 00:34:25 GMT - info: [WorkerStateManager] Storage worker reports no key for: /shared/declarative-onboarding
Sat, 27 Mar 2021 00:34:26 GMT - info: [f5-declarative-onboarding: doUtil.js] Platform: BIG-IP
Sat, 27 Mar 2021 00:34:26 GMT - info: [f5-declarative-onboarding: restWorker.js] Initial startup
Sat, 27 Mar 2021 00:34:26 GMT - config: [RestWorker] /shared/declarative-onboarding has started. Name:RestWorker
Sat, 27 Mar 2021 00:34:26 GMT - finest: [restnodedOdataAdapter] Forwarder notify callback: {"external":"/mgmt/shared/declarative-onboarding","internal":"/shared/declarative-onboarding","port":8105,"apiStatus":"NO_STATUS"}
Sat, 27 Mar 2021 00:34:31 GMT - finest: socket 185 closed
```

**Comment by JeffGiroux** [comment]
restjavad logs

```
[SEVERE][96][27 Mar 2021 00:34:24 UTC][8100/shared/iapp/package-installer-tasks PackageInstallerTaskWorker] move /var/config/rest/tmp.T7EN7O/var/config/rest/iapps/f5-declarative-onboarding -> /var/config/rest/iapps/f5-declarative-onboarding
[I][97][27 Mar 2021 00:34:24 UTC][8100/shared/iapp/template-loader IAppTemplateLoaderTaskCollectionWorker] No templates found for app f5-declarative-onboarding
[WARNING][98][27 Mar 2021 00:34:28 UTC][8100/shared/publisher PublicationWorker] submitMessageToSubscribers failed for selfLink : https://localhost/mgmt/tm/cm/device/~Common~bigip1, method: PATCH. exception: java.net.ConnectException: Connection refused.
[WARNING][99][27 Mar 2021 00:34:46 UTC][8100/shared/publisher PublicationWorker] submitMessageToSubscribers failed for selfLink : , method: PUT. exception: java.net.ConnectException: Connection refused.
```

**Comment by JeffGiroux** [comment]
my qkview - https://ihealth.f5.com/qkview-analyzer/qv/15730125/status/overview

**Comment by mikeshimkus** [comment]
Hi Jeff, can you update your startup-script to set F5_BIGIP_RUNTIME_INIT_LOG_LEVEL to "silly" and see if you get more detail in the logs?  Seems like it could be a DO issue based on the errors.

Might also be worth trying the latest DO version, 1.17.0, that this version of runtime init supports as I know of at least one bug with DO 1.16.0.  (The next release of runtime init will support the latest version of DO.)

**Comment by JeffGiroux** [comment]
I tried newer RPM versions of the toolchain but same results. I'll try again with log set to silly.

with newer version...still stops after DO...

```
2021-03-29T18:08:44.886Z [26162]: info: Executing install operations.
2021-03-29T18:08:44.895Z [26162]: info: Installing - do 1.19.0
2021-03-29T18:08:47.828Z [26162]: info: Installing - as3 3.26.0
```

**Comment by JeffGiroux** [comment]
Thx @mikeshimkus,

Things I changed to allow for successful deployment

1. I changed restjavad from 1000 to 500.
runtime-init-conf.yaml
```
pre_onboard_enabled:
  - name: provision_rest
    type: inline
    commands:
      - /usr/bin/setdb provision.extramb 500
      - /usr/bin/setdb restjavad.useextramb true
```
2. Changed BIG-IP instance type from DS3 to DS4
snippet...
```
	"variables": {
		"instanceType": "Standard_DS4_v2",
```
3. Updated RPM versions
```
extension_packages: 
  install_operations:
    - extensionType: do
      extensionVersion: 1.19.0
      extensionUrl: https://github.com/F5Networks/f5-declarative-onboarding/releases/download/v1.19.0/f5-declarative-onboarding-1.19.0-2.noarch.rpm
    - extensionType: as3
      extensionVersion: 3.26.0
      extensionUrl: https://github.com/F5Networks/f5-appsvcs-extension/releases/download/v3.26.0/f5-appsvcs-3.26.0-5.noarch.rpm
    - extensionType: ts
      extensionVersion: 1.18.0
      extensionUrl: https://github.com/F5Networks/f5-telemetry-streaming/releases/download/v1.18.0/f5-telemetry-1.18.0-2.noarch.rpm
```
