### ISSUE TITLE
fails with data should be object colon in tmsh post-onboard

### ISSUE THREAD

**Issue by JeffGiroux** [F5Networks/f5-bigip-runtime-init#19]
Trying to do a tmsh command to add a routing prefix-list in post-onboard. I have other command that work fine. When I try to do the following command, runtime init fails.

```
post_onboard_enabled:
  - name: router_bgp
    type: inline
    commands:
      - tmsh create net routing prefix-list myPrefixList1 { entries add { 10 { action permit prefix 10.0.0.0/8 prefix-len-range 16: } } route-domain 0 }
      - tmsh create net routing bgp myBGP local-as 65530 peer-group add { Neighbor { address-family { ipv4 { prefix-list { out myPrefixList1 } soft-reconfiguration-inbound enabled } } ebgp-multihop 2 remote-as 65515 } } neighbor add { 10.255.255.4 { peer-group Neighbor } 10.255.255.5 { peer-group Neighbor } } address-family { ipv4 { redistribute add { kernel } aggregate-address add { 10.100.0.0/16 { summary-only enabled } 10.101.0.0/16 { summary-only enabled } 10.102.0.0/16 { summary-only enabled } } } } graceful-restart { restart-time 120 }
  - name: create_virtual_server
    type: inline
    commands:
      - tmsh create ltm virtual 10.100.0.0 destination 10.100.0.0:any mask 255.255.0.0
      - tmsh create ltm virtual 10.101.0.0 destination 10.101.0.0:any mask 255.255.0.0
      - tmsh create ltm virtual 10.102.0.0 destination 10.102.0.0:any mask 255.255.0.0
  - name: route_advertise_virtual_servers
    type: inline
    commands:
      - tmsh modify ltm virtual-address all arp disabled icmp-echo disabled route-advertisement selective traffic-group none
      - tmsh save sys config
```

Error:
```
2021-05-21T02:23:33.725Z [5672]: info: Invalid declaration: "data should be object"
```

## troubleshooting
I remove the prefix list creation in post_onboard block router_bgp and runtime init starts this time, but then runtime init fails saying the prefix list is missing.

Error:
```
01071c50:3: Object (ipv4) reference (myPrefixList1) must be in the same route-domain (/Common/0)
```

## Related
Possibly related to how API is intepreting new routing API for bgp and prefix list. See other ticket where DO is expecting integer for prefix list value. What does runtime init expect for tmsh commands and colons?
https://github.com/F5Networks/f5-declarative-onboarding/issues/237

**Comment by JeffGiroux** [comment]
I just tested this and it works...using "16:32" instead of just "16:". Runtime init kicks off, and successfully creates all objects.

```
post_onboard_enabled:
  - name: router_bgp
    type: inline
    commands:
      - tmsh create net routing prefix-list myPrefixList1 { entries add { 10 { action permit prefix 10.0.0.0/8 prefix-len-range 16:32 } } route-domain 0 }

```

All commands now produce following. Notice prefix list is my intended results which is "ge 16". I used the value 16:32 in the tmsh command.

```
router bgp 65530
 bgp graceful-restart restart-time 120
 aggregate-address 10.100.0.0/16 summary-only
 aggregate-address 10.101.0.0/16 summary-only
 aggregate-address 10.102.0.0/16 summary-only
 redistribute kernel
 neighbor Neighbor peer-group
 neighbor Neighbor remote-as 65515
 neighbor Neighbor ebgp-multihop 2
 no neighbor Neighbor capability route-refresh
 neighbor Neighbor soft-reconfiguration inbound
 neighbor Neighbor prefix-list /Common/myPrefixList1 out
 neighbor 10.255.255.4 peer-group Neighbor
 neighbor 10.255.255.5 peer-group Neighbor
 !
 address-family ipv6
 neighbor Neighbor activate
 no neighbor 10.255.255.4 activate
 no neighbor 10.255.255.4 capability graceful-restart
 no neighbor 10.255.255.5 activate
 no neighbor 10.255.255.5 capability graceful-restart
 exit-address-family
!
ip route 0.0.0.0/0 10.255.10.1
!
ip prefix-list /Common/myPrefixList1 seq 10 permit 10.0.0.0/8 ge 16
```

## Suggestion
Still suggest that runtime init intepret a 16: similar to how the tmsh command line does in which 16: is allowed.

snip from tmsh command help
```
Values:
  Enter a valid prefix range. Example for IPv4:
    1:32                       ge 1 and le 32
    1:                         ge 1
    :32                        le 32
    32                         ge 32 le 32
  For IPv6:
    1:128                      ge 1 and le 128
```
