### ISSUE TITLE
Need to pull ENI IP address without mask

### ISSUE THREAD

**Issue by grf5** [F5Networks/f5-bigip-runtime-init#20]
When polling the AWS meta-data service for local-ipv4s, I receive back the full IP address of the interface. I see that in this implementation, the CIDR mask is being extracted from the local-subnet-ipv4-cidr string and appended. I have a use case where I need to create self IPs with a route-domain, and this makes it very difficult as I can't simply assign the IP to one variable and the mask to another, then concatenate them with a route domain %n added.

**Comment by grf5** [comment]
My workaround for extracting the IP and MASK seperately:

```bash
tmsh create net self inband-mgmt address `printf {{{ MGMT_IP }}} | cut -d "/" -f1`%1/`printf {{{ MGMT_IP }}} | cut -d "/" -f2` vlan dataplane allow-service all
```

**Comment by shyawnkarim** [comment]
Thank you for reporting this issue. We are now tracking this internally with ID ESECLDTPLT-2730.

**Comment by JeffGiroux** [comment]
I'm trying to assign the self IP as a virtual server address. You cannot have anything other than a /32 when you assign the self IP as a virtual address. As a result of the metadata retrieval getting /mask, I get an error when I try posting AS3 with selfIP + mask. 

What is status of this bug?

/Common/Shared/asg_healthCheck_vs destination 10.0.11.86 and netmask 255.255.255.0 are not valid

**Comment by JeffGiroux** [comment]
## Workaround

I do this before bigip runtime init posts the YAML.

# Retrieve self IP and update yaml declaration
SELF_IP=$(egrep fixed-address /var/lib/dhclient/dhclient.leases | head -1 | grep -oE '[^ ]+$' | tr -d ';' )
sed -i "s/\$SELF_IP/$SELF_IP/g" /config/cloud/runtime-init-conf.yaml

My yaml file has this partion within as3
```
          Common:
            class: Tenant
            Shared:
              class: Application
              template: shared
              asg_healthCheck_rule:
                remark: Respond to ASG health check
                class: iRule
                iRule: "when CLIENT_ACCEPTED {\n  TCP::close\n}"
              asg_healthCheck_vs:
                class: Service_TCP
                remark: ASG Health Check VS
                virtualPort: 8080
                virtualAddresses:
                  - $SELF_IP
```

When the yaml posts, it already includes the replaced IP with ONLY the self IP...no mask. This works for me for now.

**Comment by JeffGiroux** [comment]
This same thing happens in Azure for self IP. It pulls IP/mask.

**Comment by f5-applebaum** [comment]
the ipcalc filter needs to return "Address:" 

ex. 
https://github.com/rs/node-netmask/blob/master/example/ipcalc.coffee#L7

```
$ ipcalc 192.168.1.11/24
Address:   192.168.1.11         11000000.10101000.00000001. 00001011
Netmask:   255.255.255.0 = 24   11111111.11111111.11111111. 00000000
Wildcard:  0.0.0.255            00000000.00000000.00000000. 11111111
=>
Network:   192.168.1.0/24       11000000.10101000.00000001. 00000000
HostMin:   192.168.1.1          11000000.10101000.00000001. 00000001
HostMax:   192.168.1.254        11000000.10101000.00000001. 11111110
Broadcast: 192.168.1.255        11000000.10101000.00000001. 11111111
Hosts/Net: 254                   Class C, Private Internet
```

**Comment by codygreen** [comment]
Please prioritize this issue - it prevents us from creating a device group or device trust using runtime-init and DO.

**Comment by codygreen** [comment]
Another workaround:

```yaml
runtime_parameters:
      - name: MGMT_IP
        type: url
        value: http://169.254.169.254/latest/meta-data/local-ipv4
```
