### ISSUE TITLE
Skip installation delay when package is already installed

### ISSUE THREAD

**Issue by grf5** [F5Networks/f5-bigip-runtime-init#21]
For speed of troubleshooting, it would be great to have the extension installation delay skipped if the package is already installed:

Snippet:
```
extension_packages:
    install_operations:
        - extensionType: do
          extensionVersion: 1.21.1
        - extensionType: as3
          extensionVersion: 3.29.0
        - extensionType: ts
          extensionVersion: 1.20.1
```

Result:
```
2021-07-29T18:04:22.378Z [12809]: silly: package is already installed
2021-07-29T18:04:22.379Z [12809]: silly: Extension installation delay is set to 10000 milliseconds
```
