### ISSUE TITLE
Azure REGION metadata is wrong

### ISSUE THREAD

**Issue by JeffGiroux** [F5Networks/f5-bigip-runtime-init#23]
The metadata parameters listed for REGION only list an example for AWS. The Azure cloud has a different endpoint URL for metadata.

https://docs.microsoft.com/en-us/azure/virtual-machines/linux/instance-metadata-service

Using the curl example in the link above, you can find REGION by querying the following metadata link.

```
curl -H Metadata:true --noproxy "*" "http://169.254.169.254/metadata/instance/compute/location?api-version=2017-08-01&format=text"

westus2
```

As you can see, you receive "westus2" back. Please update docs to reflect REGION accurate example for Azure metadata.

**Comment by JeffGiroux** [comment]
The runtime yaml file block will look like this

```
  - name: REGION
    type: url
    value: http://169.254.169.254/metadata/instance/compute/location?api-version=2021-05-01&format=text
    headers:
      - name: Metadata
        value: true
```
