### ISSUE TITLE
ADMIN_PASS not being set by AWS secret

### ISSUE THREAD

**Issue by mikeoleary** [F5Networks/f5-bigip-runtime-init#3]
# Description
I am trying to use f5-bigip-runtime-init to set my ADMIN_PASS from a AWS secret. It appears that f5-bigip-runtime-init finishes successfully but my admin password is not updated to the value of my AWS secret.

I am not sure what to expect when I log into the device, but after I change the password via command line and log into the GUI, I still see the Setup Utility. I need to click through the license page and resource provisioning, where only LTM is checked by default (despite my configuring ASM in the yaml file). Is the runtime-init configuration actually working? Interestingly:
- there are no mentions of failures in the log file, and the log file finishes by seeing TEEM report of success.
- the Automation Toolchain RPMs are already installed when I log in after deployment. So it is at least partly working.

What am I doing wrong?

# Documentation questions
In [this example](https://github.com/F5Networks/f5-bigip-runtime-init#aws-terraform-snippet) of setting a password via AWS secret manager, you refer to a Terraform secret version (ie, the secret version and not the secret itself). I have found that I need to pass the ARN of the AWS secret (ie, not the "name" of the secret but the "id" or the "arn") and this must be the secret, not the secret version. Does that make sense? I think the documentation could be clearer here, both that the ARN needs to be provided in the YAML file and that it's the secret, not the secret version.

# Troubleshooting done
I'm using silly log levels and cannot find any failures and I believe the following:
- I am using a string that I know is okay to use as a BIG-IP admin password. I can change the password to this value via TMSH, and I can also have this password change automated by using a python script to pull it from AWS Secrets Manager and setting this via user_data. But I would prefer to put as much onboarding in bigip-runtime-init as possible.
- I can see that BIG-IP is making an API call to retrieve secret value from AWS. CloudTrail shows that the Ec2 instance retrieves the value of the secret, and this API call appears to be successful. So I believe that fetching the value of the secret is not the problem.
- The IAM role that is attached to the EC2 instance only allows the action secretsmanager:GetSecretValue on the resource required. This is enough for me to use other methods (AWS cmd line tool and python script) to get the secret value, and I can see via CloudTrail that when using runtime-init, the API calls to get the secret appear successful. 
- /var/log/cloud/bigIpRuntimeInit.log shows a failure to find MAC address for interfaces 1.1 and 1.2 - is this a concern?

### My IAM role policy document 
```
data "aws_iam_policy_document" "bigip_policy" {
  version = "2012-10-17"
  statement {
    actions = [
      "secretsmanager:GetSecretValue"
    ]

    resources = [
      aws_secretsmanager_secret.bigip_password.arn
    ]
  }
}
```

### My YAML file
````yaml
---
runtime_parameters:
  - name: HOST_NAME
    type: metadata
    metadataProvider:
        environment: aws
        type: compute
        field: hostname
  - name: ADMIN_PASS
    type: secret
    secretProvider:
      environment: aws
      type: SecretsManager
      version: AWSCURRENT
      secretId: ${secret_id}
pre_onboard_enabled:
  - name: provision_rest
    type: inline
    commands:
      - /usr/bin/setdb provision.extramb 500
      - /usr/bin/setdb restjavad.useextramb true
  - name: provision_modules
    type: inline
    commands:
      - echo 'sys provision asm { level nominal }' >> bigip_base.conf
extension_packages:
  install_operations:
    - extensionType: do
      extensionVersion: 1.15.0
    - extensionType: as3
      extensionVersion: 3.20.0
    - extensionType: ts
      extensionVersion: 1.14.0
    - extensionType: cf
      extensionVersion: 1.5.0


    - extensionType: ilx
      extensionUrl: https://github.com/F5Networks/f5-appsvcs-templates/releases/download/v1.3.0/f5-appsvcs-templates-1.3.0-1.noarch.rpm
      extensionVersion: 1.3.0
      extensionVerificationEndpoint: /mgmt/shared/fast/info
extension_services:
  service_operations: []
````
