### ISSUE TITLE
is there a way to pass a set of variables into the config file?

### ISSUE THREAD

**Issue by mwardbopp** [F5Networks/f5-bigip-runtime-init#38]
For a single variable I can resolve via type:url with plain text file containing the value, is there a way to provide a set of variables in the single file?

runtime_parameters:
  - name: BIGIQ_HOST
    type: url
    value: https://wardbopp-s3.s3.eu-west-1.amazonaws.com/10.0.1.6.json 
  - name: BIGIQ_LIC_MGR
    type: url
    value: https://wardbopp-s3.s3.eu-west-1.amazonaws.com/10.0.1.6.json
  - name: BIGIQ_LIC_POOL
    type: url
    value: https://wardbopp-s3.s3.eu-west-1.amazonaws.com/10.0.1.6.json

When I try to use a file that looks like this:
{ "BIGIQ_HOST" : "10.0.1.6",
"BIGIQ_LIC_MGR" : "licensemgr",
"BIGIQ_LIC_POOL" : "aws"
}
I get object Object in the rendered DO configuration.

"bigIqHost":"[object Object]","bigIqUsername":"[object Object]","bigIqPassword":"********","licensePool":"[object Object]"

**Comment by mikeshimkus** [comment]
Hi @mwardbopp, have you tried referencing the parameter output using dot notation, e.g.:

```yaml
name: MY_CONFIG
type: url
value: https://wardbopp-s3.s3.eu-west-1.amazonaws.com/10.0.1.6.json
```

Then in your services:
```yaml
My_License:
  bigIqHost: '{{{MY_CONFIG.BIGIQ_HOST}}}'
  bigIqPassword: '{{{BIGIQ_PASSWORD}}}'
  bigIqUsername: admin
  class: License
  hypervisor: aws
  licensePool: '{{{MY_CONFIG.BIGIQ_LIC_POOL}}}'
  licenseType: licensePool
  reachable: false
  skuKeyword1: F5-BIG-MSP-BT-1G
  tenant: myTenant
  unitOfMeasure: hourly
```
If this doesn't work it probably means we just need to convert whatever is returned by the URL param to an object during rendering.
