### ISSUE TITLE
GCP hostname fails to pull metadata - invalid declaration

### ISSUE THREAD

**Issue by JeffGiroux** [F5Networks/f5-bigip-runtime-init#40]
User tries to retrieve hostname as metadata. This works in AWS and Azure. Using same fields for Google results in runtime init error.

This results in a lack across cloud parity. Please correct and allow all CSP to query hostname or something common. Also, update docs with proper example.

error...
```
Invalid declaration: "data.runtime_parameters[15].metadataProvider.field should be equal to one of the allowed values, data.runtime_parameters[15].metadataProvider should match \"then\" schema"
```

Example code block...
```
  - name: HOST_NAME
    type: metadata
    metadataProvider:
      environment: gcp
      type: compute
      field: hostname
```

## Workaround
You can query the metadata URL in a manual way to get hostname. Example...
```
        - name: SHORTNAME
          type: url
          value: http://169.254.169.254/computeMetadata/v1/instance/name
          returnType: string
          headers:
            - name: Metadata-Flavor
              value: Google
```
