### ISSUE TITLE
extension_services: "type" field does not accept "file" as value

### ISSUE THREAD

**Issue by adityoari** [F5Networks/f5-bigip-runtime-init#47]
Version 1.5.1 fails when `file` is used for `type` setting in `extension_services.service_operations` with the following errors:
```
"result": "FAILURE",
		"resultSummary": "Invalid declaration: \"data.extension_services.service_operations[0].type should be equal to one of the allowed values\"",
```
Same declaration is successful if `type` is changed to `url`.
README clearly mentions that `file` is a valid value, so please update either the code or the misleading documentation:

**Comment by adityoari** [comment]
# Non-working config:
```
controls:
  logLevel: silly
  logFilename: /var/log/cloud/bigIpRuntimeInit.log
extension_packages:
  install_operations:
  - extensionType: do
    extensionVersion: 1.27.1
extension_services:
  service_operations:
  - extensionType: do
    type: file
    value: file:///var/tmp/do.json
```

# Working config:
```
controls:
  logLevel: silly
  logFilename: /var/log/cloud/bigIpRuntimeInit.log
extension_packages:
  install_operations:
  - extensionType: do
    extensionVersion: 1.27.1
extension_services:
  service_operations:
  - extensionType: do
    type: url
    value: file:///var/tmp/do.json
```
