### ISSUE TITLE
F5 onboarding is failing

### ISSUE THREAD

**Issue by KodiakF5Team** [F5Networks/f5-bigip-runtime-init#49]
We are trying to do onboarding with IPv6 , As per azure IPv6 can be defined as secondary IP,
it is failing with error  "Cannot read property '0' of undefined"

[error log.txt](https://github.com/F5Networks/f5-bigip-runtime-init/files/10110892/error.log.txt)
[runtime_init.conf.txt](https://github.com/F5Networks/f5-bigip-runtime-init/files/10110893/runtime_init.conf.txt)
[bigIpRuntimeInit.log](https://github.com/F5Networks/f5-bigip-runtime-init/files/10110895/bigIpRuntimeInit.log)

**Comment by mikeshimkus** [comment]
Hi @KodiakF5Team, yes, I can see in the code where that wouldn't work.  I have created internal issue #3235 to track the fix. Can you try the following as a workaround:

```
- name: SELF_IP_EXTERNAL7
  type: url
  query: ipv6.ipAddress[0]
  value: 'http://169.254.169.254/metadata/instance/network/interface/6?api-version=2017-08-01'
  headers:
    - name: Metadata
      value: true
```
