### ISSUE TITLE
extensionUrl not working with remote URLs with BIG-IP 15.1.2

### ISSUE THREAD

**Issue by chen23** [F5Networks/f5-bigip-runtime-init#5]
When you specify an external URL for extensionUrl the process hangs on installing the extension.  This occurs on 15.1.2, but does not occur on 15.1.0.4

Example that fails
```
runtime_parameters: []
pre_onboard_enabled:
  - name: provision_rest
    type: inline
    commands:
      - /usr/bin/setdb provision.extramb 500
      - /usr/bin/setdb restjavad.useextramb true
      - /usr/bin/setdb setup.run false
extension_packages:
  install_operations:
    - extensionType: as3
      extensionVersion: 3.24.0
      extensionUrl: https://github.com/F5Networks/f5-appsvcs-extension/releases/download/v3.24.0/f5-appsvcs-3.24.0-5.noarch.rpm
extension_services:
    service_operations: []
```
example that works
```
---
runtime_parameters: []
pre_onboard_enabled:
  - name: provision_rest
    type: inline
    commands:
      - /usr/bin/setdb provision.extramb 500
      - /usr/bin/setdb restjavad.useextramb true
      - /usr/bin/setdb setup.run false
extension_packages:
  install_operations:
    - extensionType: as3
      extensionVersion: 3.24.0
      extensionUrl: file:///var/config/rest/downloads/f5-appsvcs-3.24.0-5.noarch.rpm
extension_services:
    service_operations: []
```
