### ISSUE TITLE
script halts with error 'Device is not licensed yet'

### ISSUE THREAD

**Issue by thepowercoders** [F5Networks/f5-bigip-runtime-init#50]
## Version
f5-bigip-runtime-init-1.6.0-1.gz.run

## Issue

I am trying to automate build of bigip VE in Microsoft Azure using the custom-data parameter to run a script which will download and run bigip-runtime-init to install packages (as3, do, ts) and then run a DO statement. However, the script always halts with the following error in: `/var/log/cloud/bigIpRuntimeInit.log`:

`2023-02-28T16:18:46.234Z [9906]: error: Device is not licensed yet`

This seems to occur just after the script has processed extension_packages / install_operations and installed DO, AS3 and TS.

I originally had the license key in the DO statement but this failed so I also tried to put it into the YAML file itself - so I now have this:

```
extension_services:
  service_operations:
    - extensionType: do
      type: inline
      value:
        schemaVersion: 1.0.0
        class: Device
        async: true
        Common:
          class: Tenant
          deviceLicense:
            class: License
            licenseType: regKey
            regKey: 'SWEAX-BUFRF-XXXXX-XXXXX-XXXXX'
    - extensionType: do
      type: url
      value: file:///config/cloud/do_w_admin.json
```

- where my do_w_admin.json (which is a DO statement) also has the license object (as per snippet below - actual reg key used has been anonymised):

```
    "Common": {
        "class": "Tenant",
        "deviceLicense": {
            "class": "License",
            "licenseType": "regKey",
            "regKey": "SWEAX-BUFRF-XXXXX-XXXXX-XXXXX"
        },
```

What is odd is that if I just log into the device once it is built and run the bigip-runtime init script manually from the command line, I get this:

```
2023-02-28T17:09:04.604Z [3423]: info: Creating - do 1.36.0 {"schemaVersion":"1.0.0","class":"Device","async":true,"Common":{"class":"Tenant","deviceLicense":{"class":"License","licenseType":"regKey","regKey":"SWEAX-BUFRF-XXXXX-XXXXX-XXXXX"}}}
```
... and this then runs and appears license the device - the DO statement is processed and the box is configured. However, when I log into it, it says it is unlicensed again!

When I check the status of DO tasks by calling: `https://<device-public-ip>/mgmt/shared/declarative-onboarding/task/` it returns a 200 OK with the license showing in the response - but the box is unlicensed.

**Comment by antonywm** [comment]
update - I've actually got around this by adding the following to the pre_onboard_enabled section of the config:

```
pre_onboard_enabled:
  - name: license_device
    type: inline
    commands:
      - /usr/bin/tmsh install /sys license registration-key SWEAX-BUFRF-XXXXX-XXXXX-XXXXX
```

I've then removed the license config from the DO statement and this seems to allow the script to fully complete.

Would be good to confirm this is the expected behavior as all the examples I've seen on clouddocs and in this git repo show the license being provisioned within the DO statement.
