### ISSUE TITLE
Runtime init failed with runtime error "Server Error in '/' Application."

### ISSUE THREAD

**Issue by RavinderReddyF5** [F5Networks/f5-bigip-runtime-init#7]
**BIGIP Version:**
```
[bigipuser@localhost:Active:Standalone] ~ # tmsh show /sys version

Sys::Version
Main Package
  Product     BIG-IP
  Version     14.1.2.6
  Build       0.0.2
  Edition     Point Release 6
  Date        Fri Jun  5 11:36:46 PDT 2020
```

**runtime-init-conf.yaml** :

```
runtime_parameters:
  - name: ADMIN_PASS
    type: secret
    secretProvider:
      environment: azure
      type: KeyVault
      vaultUrl: https://ravikeyval-05ef.vault.azure.net/
      secretId: https://ravikeyval-05ef.vault.azure.net/secrets/RaviKeyValSec-05ef/060709b5de6b44fd9254bef1a56153aa
pre_onboard_enabled:
  - name: provision_rest
    type: inline
    commands:
      - /usr/bin/setdb provision.extramb 500
      - /usr/bin/setdb restjavad.useextramb true
extension_packages:
    install_operations:
        - extensionType: do
          extensionVersion: 1.16.0
        - extensionType: as3
          extensionVersion: 3.23.0
        - extensionType: ts
          extensionVersion: 1.12.0
        - extensionType: cf
          extensionVersion: 1.6.1
extension_services:
  service_operations:
    - extensionType: do
      type: url
      value: https://raw.githubusercontent.com/F5Networks/f5-bigip-runtime-init/main/examples/declarations/do_w_admin.json
    - extensionType: as3
      type: url
      value: https://raw.githubusercontent.com/F5Networks/f5-bigip-runtime-init/main/examples/declarations/as3.json
post_onboard_enabled: []

```

Error logs:

```
[bigipuser@localhost:Active:Standalone] ~ # f5-bigip-runtime-init --config-file /config/cloud/runtime-init-conf.yaml --skip-telemetry
2020-12-21T17:08:34.473Z [19406]: info: Configuration file: /config/cloud/runtime-init-conf.yaml
2020-12-21T17:08:34.481Z [19406]: info: F5 Telemetry is disabled.
2020-12-21T17:08:34.482Z [19406]: info: Validating provided declaration
2020-12-21T17:08:34.545Z [19406]: info: Successfully validated declaration
2020-12-21T17:08:34.548Z [19406]: silly: Making request: GET http://localhost:8100/mgmt/tm/sys/ready verifyTls: true
2020-12-21T17:08:34.604Z [19406]: silly: Request response: 200 {"kind":"tm:sys:ready:readystats","selfLink":"https://localhost/mgmt/tm/sys/ready?ver=14.1.2.6","entries":{"https://localhost/mgmt/tm/sys/ready/0":{"nestedStats":{"entries":{"configReady":{"description":"yes"},"licenseReady":{"description":"yes"},"provisionReady":{"description":"yes"}}}}}}
2020-12-21T17:08:34.605Z [19406]: info: Resolving parameters
2020-12-21T17:08:34.904Z [19406]: silly: Making request: GET http://169.254.169.254/metadata/instance?api-version=2017-08-01 verifyTls: true
2020-12-21T17:08:34.941Z [19406]: silly: Request response: 200 {"compute":{"location":"eastus","name":"tf-azure-bigip-1nic-ed37-f5vm01","offer":"f5-big-ip-best","osType":"Linux","placementGroupId":"","platformFaultDomain":"0","platformUpdateDomain":"0","publisher":"f5-networks","resourceGroupName":"tf-azure-bigip-rg-05ef","sku":"f5-bigip-virtual-edition-200m-best-hourly","subscriptionId":"d31e4e54-7577-4f43-b407-bae6cc0f4f55","tags":"Name:tf-azure-bigip-1nic-ed37-f5vm01;source:terraform","version":"14.1.206000","vmId":"83912589-a45f-4a44-a4d2-c584d0d0d4f1","vmSize":"Standard_DS3_v2"},"network":{"interface":[{"ipv4":{"ipAddress":[{"privateIpAddress":"10.2.1.4","publicIpAddress":""}],"subnet":[{"address":"10.2.1.0","prefix":"24"}]},"ipv6":{"ipAddress":[]},"macAddress":"000D3A176AA6"}]}}
2020-12-21T17:08:35.068Z [19406]: error: <!DOCTYPE html>
<html>
    <head>
        <title>Runtime Error</title>
        <meta name="viewport" content="width=device-width" />
        <style>
         body {font-family:"Verdana";font-weight:normal;font-size: .7em;color:black;}
         p {font-family:"Verdana";font-weight:normal;color:black;margin-top: -5px}
         b {font-family:"Verdana";font-weight:bold;color:black;margin-top: -5px}
         H1 { font-family:"Verdana";font-weight:normal;font-size:18pt;color:red }
         H2 { font-family:"Verdana";font-weight:normal;font-size:14pt;color:maroon }
         pre {font-family:"Consolas","Lucida Console",Monospace;font-size:11pt;margin:0;padding:0.5em;line-height:14pt}
         .marker {font-weight: bold; color: black;text-decoration: none;}
         .version {color: gray;}
         .error {margin-bottom: 10px;}
         .expandable { text-decoration:underline; font-weight:bold; color:navy; cursor:hand; }
         @media screen and (max-width: 639px) {
          pre { width: 440px; overflow: auto; white-space: pre-wrap; word-wrap: break-word; }
         }
         @media screen and (max-width: 479px) {
          pre { width: 280px; }
         }
        </style>
    </head>

 

    <body bgcolor="white">

 

            <span><H1>Server Error in '/' Application.<hr width=100% size=1 color=silver></H1>

 

            <h2> <i>Runtime Error</i> </h2></span>

 

            <font face="Arial, Helvetica, Geneva, SunSans-Regular, sans-serif ">

 

            <b> Description: </b>An application error occurred on the server. The current custom error settings for this application prevent the details of the application error from being viewed remotely (for security reasons). It could, however, be viewed by browsers running on the local server machine.
            <br><br>

 

            <b>Details:</b> To enable the details of this specific error message to be viewable on remote machines, please create a &lt;customErrors&gt; tag within a &quot;web.config&quot; configuration file located in the root directory of the current web application. This &lt;customErrors&gt; tag should then have its &quot;mode&quot; attribute set to &quot;Off&quot;.<br><br>

 

            <table width=100% bgcolor="#ffffcc">
               <tr>
                  <td>
                      <code><pre>

 

&lt;!-- Web.Config Configuration File --&gt;

 

&lt;configuration&gt;
    &lt;system.web&gt;
        &lt;customErrors mode=&quot;Off&quot;/&gt;
    &lt;/system.web&gt;
&lt;/configuration&gt;</pre></code>

 

                  </td>
               </tr>
            </table>

 

            <br>

 

            <b>Notes:</b> The current error page you are seeing can be replaced by a custom error page by modifying the &quot;defaultRedirect&quot; attribute of the application&#39;s &lt;customErrors&gt; configuration tag to point to a custom error page URL.<br><br>

 

            <table width=100% bgcolor="#ffffcc">
               <tr>
                  <td>
                      <code><pre>

 

&lt;!-- Web.Config Configuration File --&gt;

 

&lt;configuration&gt;
    &lt;system.web&gt;
        &lt;customErrors mode=&quot;RemoteOnly&quot; defaultRedirect=&quot;mycustompage.htm&quot;/&gt;
    &lt;/system.web&gt;
&lt;/configuration&gt;</pre></code>

 

                  </td>
               </tr>
            </table>

 

            <br>

 

    </body>
</html>
 
```
